### ISSUE TITLE
Upgrade Request for terraform-provider-controltower

### ISSUE THREAD

**Issue by Phylu** [theurichde/theurichde#2]
Hi @theurichde,

I can see that you previously worked on https://github.com/idealo/terraform-provider-controltower
First of all: Thanks a lot for the module. It is really cool!

Unfortunately, the currently released version of the terraform provider does not work well with AWS SSO Sessions as described here: https://github.com/idealo/terraform-provider-controltower/issues/211

Can you tell me whether there are any plans to upgrade aws-sdk-go to v2? If not, I need to think about forking your provider as it unfortunately became unusable. :(

Cheers,
Phylu

**Comment by theurichde** [comment]
Hi @Phylu. Thanks for reaching out. 

Unfortunately, I have to disappoint you. 

This provider is from idealos perspective not maintained anymore. I will reach out to the colleagues, that they add a maintenance note in the repo or archive it completely.

Good luck with your upgrade!

Sidenote: Referring to the issue itself; You tried to set `sso_start_url` and `sso_region` on the `default` profile, too, yes?

**Comment by Phylu** [comment]
Thanks a lot for the info, even though, I would have hoped for a better answer. :D

With the new sso session setup, it is not possible to set `sso_start_url` and `sso_region` on the profile anymore, but only on the `sso-session`. This is what is actually producing the issue.
